version: '3.8'

services:
  # Сервис базы данных
  db:
    image: postgres:15-alpine
    container_name: vGarage_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vGarage
    ports:
      - "5432:5432"
    volumes:
      - vGarage_db_data:/var/lib/postgresql/data

# ОБЯЗАТЕЛЬНО: объявление тома, чтобы данные не пропадали после рестарта
volumes:
  vGarage_db_data: